import platform
from collections.abc import Mapping
from functools import partial
from typing import Any

import pytest

from odbcffi.odbc.enums import InfoType, SQLDataType
from tests.drivers.base import DriverTest

pytestmark = pytest.mark.skipif(platform.system() != "Windows", reason="MDAC is Windows only.")


@pytest.fixture(scope="module")
def driver() -> str:
    return "SQL Server"


class TestMDAC(DriverTest):
    @property
    def expected_sql_get_info_w_return_values(self) -> Mapping[InfoType, Any]:
        return {
            InfoType.SQL_ACCESSIBLE_PROCEDURES: "",
            InfoType.SQL_ACCESSIBLE_TABLES: "",
            InfoType.SQL_ACTIVE_ENVIRONMENTS: "",
            InfoType.SQL_AGGREGATE_FUNCTIONS: "",
            InfoType.SQL_ALTER_DOMAIN: "",
            InfoType.SQL_ALTER_TABLE: "",
            InfoType.SQL_ASYNC_DBC_FUNCTIONS: "",
            InfoType.SQL_ASYNC_MODE: "",
            InfoType.SQL_ASYNC_NOTIFICATION: "",
            InfoType.SQL_BATCH_ROW_COUNT: "",
            InfoType.SQL_BATCH_SUPPORT: "",
            InfoType.SQL_BOOKMARK_PERSISTENCE: "",
            InfoType.SQL_CATALOG_LOCATION: "",
            InfoType.SQL_CATALOG_NAME: "",
            InfoType.SQL_CATALOG_NAME_SEPARATOR: "",
            InfoType.SQL_CATALOG_TERM: "",
            InfoType.SQL_CATALOG_USAGE: "",
            InfoType.SQL_COLLATION_SEQ: "",
            InfoType.SQL_COLUMN_ALIAS: "",
            InfoType.SQL_CONCAT_NULL_BEHAVIOR: "",
            InfoType.SQL_CONVERT_BIGINT: "",
            InfoType.SQL_CONVERT_BINARY: "",
            InfoType.SQL_CONVERT_BIT: "",
            InfoType.SQL_CONVERT_CHAR: "",
            InfoType.SQL_CONVERT_DATE: "",
            InfoType.SQL_CONVERT_DECIMAL: "",
            InfoType.SQL_CONVERT_DOUBLE: "",
            InfoType.SQL_CONVERT_FLOAT: "",
            InfoType.SQL_CONVERT_FUNCTIONS: "",
            InfoType.SQL_CONVERT_GUID: "",
            InfoType.SQL_CONVERT_INTEGER: "",
            InfoType.SQL_CONVERT_INTERVAL_DAY_TIME: "",
            InfoType.SQL_CONVERT_INTERVAL_YEAR_MONTH: "",
            InfoType.SQL_CONVERT_LONGVARBINARY: "",
            InfoType.SQL_CONVERT_LONGVARCHAR: "",
            InfoType.SQL_CONVERT_NUMERIC: "",
            InfoType.SQL_CONVERT_REAL: "",
            InfoType.SQL_CONVERT_SMALLINT: "",
            InfoType.SQL_CONVERT_TIME: "",
            InfoType.SQL_CONVERT_TIMESTAMP: "",
            InfoType.SQL_CONVERT_TINYINT: "",
            InfoType.SQL_CONVERT_VARBINARY: "",
            InfoType.SQL_CONVERT_VARCHAR: "",
            InfoType.SQL_CONVERT_WCHAR: "",
            InfoType.SQL_CONVERT_WLONGVARCHAR: "",
            InfoType.SQL_CONVERT_WVARCHAR: "",
            InfoType.SQL_CORRELATION_NAME: "",
            InfoType.SQL_CREATE_ASSERTION: "",
            InfoType.SQL_CREATE_CHARACTER_SET: "",
            InfoType.SQL_CREATE_COLLATION: "",
            InfoType.SQL_CREATE_DOMAIN: "",
            InfoType.SQL_CREATE_SCHEMA: "",
            InfoType.SQL_CREATE_TABLE: "",
            InfoType.SQL_CREATE_TRANSLATION: "",
            InfoType.SQL_CREATE_VIEW: "",
            InfoType.SQL_CURSOR_COMMIT_BEHAVIOR: "",
            InfoType.SQL_CURSOR_ROLLBACK_BEHAVIOR: "",
            InfoType.SQL_CURSOR_SENSITIVITY: "",
            InfoType.SQL_DATABASE_NAME: "",
            InfoType.SQL_DATA_SOURCE_NAME: "",
            InfoType.SQL_DATA_SOURCE_READ_ONLY: "",
            InfoType.SQL_DATETIME_LITERALS: "",
            InfoType.SQL_DBMS_NAME: "",
            InfoType.SQL_DBMS_VER: partial(pytest.skip, reason="Unstable return value for SQL_DBMS_VER"),
            InfoType.SQL_DDL_INDEX: "",
            InfoType.SQL_DEFAULT_TXN_ISOLATION: "",
            InfoType.SQL_DESCRIBE_PARAMETER: "",
            InfoType.SQL_DM_VER: partial(pytest.skip, reason="Unstable return value for SQL_DM_VER"),
            InfoType.SQL_DRIVER_AWARE_POOLING_SUPPORTED: "",
            InfoType.SQL_DRIVER_HDBC: "",
            InfoType.SQL_DRIVER_HDESC: "",
            InfoType.SQL_DRIVER_HENV: "",
            InfoType.SQL_DRIVER_HLIB: "",
            InfoType.SQL_DRIVER_HSTMT: "",
            InfoType.SQL_DRIVER_NAME: partial(pytest.skip, reason="Unstable return value for SQL_DRIVER_NAME"),
            InfoType.SQL_DRIVER_ODBC_VER: "",
            InfoType.SQL_DRIVER_VER: partial(pytest.skip, reason="Unstable return value for SQL_DRIVER_VER"),
            InfoType.SQL_DROP_ASSERTION: "",
            InfoType.SQL_DROP_CHARACTER_SET: "",
            InfoType.SQL_DROP_COLLATION: "",
            InfoType.SQL_DROP_DOMAIN: "",
            InfoType.SQL_DROP_SCHEMA: "",
            InfoType.SQL_DROP_TABLE: "",
            InfoType.SQL_DROP_TRANSLATION: "",
            InfoType.SQL_DROP_VIEW: "",
            InfoType.SQL_DYNAMIC_CURSOR_ATTRIBUTES1: "",
            InfoType.SQL_DYNAMIC_CURSOR_ATTRIBUTES2: "",
            InfoType.SQL_EXPRESSIONS_IN_ORDERBY: "",
            InfoType.SQL_FETCH_DIRECTION: "",
            InfoType.SQL_FILE_USAGE: "",
            InfoType.SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES1: "",
            InfoType.SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES2: "",
            InfoType.SQL_GETDATA_EXTENSIONS: "",
            InfoType.SQL_GROUP_BY: "",
            InfoType.SQL_IDENTIFIER_CASE: "",
            InfoType.SQL_IDENTIFIER_QUOTE_CHAR: "",
            InfoType.SQL_INDEX_KEYWORDS: "",
            InfoType.SQL_INFO_SCHEMA_VIEWS: "",
            InfoType.SQL_INSERT_STATEMENT: "",
            InfoType.SQL_INTEGRITY: "",
            InfoType.SQL_KEYSET_CURSOR_ATTRIBUTES1: "",
            InfoType.SQL_KEYSET_CURSOR_ATTRIBUTES2: "",
            InfoType.SQL_KEYWORDS: "",
            InfoType.SQL_LIKE_ESCAPE_CLAUSE: "",
            InfoType.SQL_LOCK_TYPES: "",
            InfoType.SQL_MAX_ASYNC_CONCURRENT_STATEMENTS: "",
            InfoType.SQL_MAX_BINARY_LITERAL_LEN: "",
            InfoType.SQL_MAX_CATALOG_NAME_LEN: "",
            InfoType.SQL_MAX_CHAR_LITERAL_LEN: "",
            InfoType.SQL_MAX_COLUMNS_IN_GROUP_BY: "",
            InfoType.SQL_MAX_COLUMNS_IN_INDEX: "",
            InfoType.SQL_MAX_COLUMNS_IN_ORDER_BY: "",
            InfoType.SQL_MAX_COLUMNS_IN_SELECT: "",
            InfoType.SQL_MAX_COLUMNS_IN_TABLE: "",
            InfoType.SQL_MAX_COLUMN_NAME_LEN: "",
            InfoType.SQL_MAX_CONCURRENT_ACTIVITIES: "",
            InfoType.SQL_MAX_CURSOR_NAME_LEN: "",
            InfoType.SQL_MAX_DRIVER_CONNECTIONS: "",
            InfoType.SQL_MAX_IDENTIFIER_LEN: "",
            InfoType.SQL_MAX_INDEX_SIZE: "",
            InfoType.SQL_MAX_PROCEDURE_NAME_LEN: "",
            InfoType.SQL_MAX_ROW_SIZE: "",
            InfoType.SQL_MAX_ROW_SIZE_INCLUDES_LONG: "",
            InfoType.SQL_MAX_SCHEMA_NAME_LEN: "",
            InfoType.SQL_MAX_STATEMENT_LEN: "",
            InfoType.SQL_MAX_TABLES_IN_SELECT: "",
            InfoType.SQL_MAX_TABLE_NAME_LEN: "",
            InfoType.SQL_MAX_USER_NAME_LEN: "",
            InfoType.SQL_MULTIPLE_ACTIVE_TXN: "",
            InfoType.SQL_MULT_RESULT_SETS: "",
            InfoType.SQL_NEED_LONG_DATA_LEN: "",
            InfoType.SQL_NON_NULLABLE_COLUMNS: "",
            InfoType.SQL_NULL_COLLATION: "",
            InfoType.SQL_NUMERIC_FUNCTIONS: "",
            InfoType.SQL_ODBC_API_CONFORMANCE: "",
            InfoType.SQL_ODBC_INTERFACE_CONFORMANCE: "",
            InfoType.SQL_ODBC_SAG_CLI_CONFORMANCE: "",
            InfoType.SQL_ODBC_SQL_CONFORMANCE: "",
            InfoType.SQL_ODBC_VER: "",
            InfoType.SQL_OJ_CAPABILITIES: "",
            InfoType.SQL_ORDER_BY_COLUMNS_IN_SELECT: "",
            InfoType.SQL_OUTER_JOINS: "",
            InfoType.SQL_PARAM_ARRAY_ROW_COUNTS: "",
            InfoType.SQL_PARAM_ARRAY_SELECTS: "",
            InfoType.SQL_POSITIONED_STATEMENTS: "",
            InfoType.SQL_POS_OPERATIONS: "",
            InfoType.SQL_PROCEDURES: "",
            InfoType.SQL_PROCEDURE_TERM: "",
            InfoType.SQL_QUOTED_IDENTIFIER_CASE: "",
            InfoType.SQL_ROW_UPDATES: "",
            InfoType.SQL_SCHEMA_TERM: "",
            InfoType.SQL_SCHEMA_USAGE: "",
            InfoType.SQL_SCROLL_CONCURRENCY: "",
            InfoType.SQL_SCROLL_OPTIONS: "",
            InfoType.SQL_SEARCH_PATTERN_ESCAPE: "",
            InfoType.SQL_SERVER_NAME: partial(pytest.skip, reason="Unstable return value for SQL_SERVER_NAME"),
            InfoType.SQL_SPECIAL_CHARACTERS: "",
            InfoType.SQL_SQL92_DATETIME_FUNCTIONS: "",
            InfoType.SQL_SQL92_FOREIGN_KEY_DELETE_RULE: "",
            InfoType.SQL_SQL92_FOREIGN_KEY_UPDATE_RULE: "",
            InfoType.SQL_SQL92_GRANT: "",
            InfoType.SQL_SQL92_NUMERIC_VALUE_FUNCTIONS: "",
            InfoType.SQL_SQL92_PREDICATES: "",
            InfoType.SQL_SQL92_RELATIONAL_JOIN_OPERATORS: "",
            InfoType.SQL_SQL92_REVOKE: "",
            InfoType.SQL_SQL92_ROW_VALUE_CONSTRUCTOR: "",
            InfoType.SQL_SQL92_STRING_FUNCTIONS: "",
            InfoType.SQL_SQL92_VALUE_EXPRESSIONS: "",
            InfoType.SQL_SQL_CONFORMANCE: "",
            InfoType.SQL_STANDARD_CLI_CONFORMANCE: "",
            InfoType.SQL_STATIC_CURSOR_ATTRIBUTES1: "",
            InfoType.SQL_STATIC_CURSOR_ATTRIBUTES2: "",
            InfoType.SQL_STATIC_SENSITIVITY: "",
            InfoType.SQL_STRING_FUNCTIONS: "",
            InfoType.SQL_SUBQUERIES: "",
            InfoType.SQL_SYSTEM_FUNCTIONS: "",
            InfoType.SQL_TABLE_TERM: "",
            InfoType.SQL_TIMEDATE_ADD_INTERVALS: "",
            InfoType.SQL_TIMEDATE_DIFF_INTERVALS: "",
            InfoType.SQL_TIMEDATE_FUNCTIONS: "",
            InfoType.SQL_TXN_CAPABLE: "",
            InfoType.SQL_TXN_ISOLATION_OPTION: "",
            InfoType.SQL_UNION: "",
            InfoType.SQL_USER_NAME: "",
            InfoType.SQL_XOPEN_CLI_YEAR: "",
        }

    @property
    def expected_sql_get_type_info_w_return_values(self) -> Mapping[SQLDataType, list[dict[str, Any]]]:
        return {
            SQLDataType.SQL_BIGINT: [],
            SQLDataType.SQL_BINARY: [],
            SQLDataType.SQL_BIT: [],
            SQLDataType.SQL_CHAR: [],
            SQLDataType.SQL_DATETIME: [],
            SQLDataType.SQL_DECIMAL: [],
            SQLDataType.SQL_DOUBLE: [],
            SQLDataType.SQL_FLOAT: [],
            SQLDataType.SQL_GUID: [],
            SQLDataType.SQL_INTEGER: [],
            SQLDataType.SQL_INTERVAL: [],
            SQLDataType.SQL_LONGVARBINARY: [],
            SQLDataType.SQL_LONGVARCHAR: [],
            SQLDataType.SQL_NUMERIC: [],
            SQLDataType.SQL_REAL: [],
            SQLDataType.SQL_SMALLINT: [],
            SQLDataType.SQL_SS_TABLE: [],
            SQLDataType.SQL_SS_TIME2: [],
            SQLDataType.SQL_SS_TIMESTAMPOFFSET: [],
            SQLDataType.SQL_SS_UDT: [],
            SQLDataType.SQL_SS_VARIANT: [],
            SQLDataType.SQL_SS_XML: [],
            SQLDataType.SQL_TIMESTAMP: [],
            SQLDataType.SQL_TINYINT: [],
            SQLDataType.SQL_TYPE_DATE: [],
            SQLDataType.SQL_TYPE_TIME: [],
            SQLDataType.SQL_TYPE_TIME_WITH_TIMEZONE: [],
            SQLDataType.SQL_TYPE_TIMESTAMP: [],
            SQLDataType.SQL_TYPE_TIMESTAMP_WITH_TIMEZONE: [],
            SQLDataType.SQL_UNKNOWN_TYPE: [],
            SQLDataType.SQL_VARBINARY: [],
            SQLDataType.SQL_VARCHAR: [],
            SQLDataType.SQL_WCHAR: [],
            SQLDataType.SQL_WLONGVARCHAR: [],
            SQLDataType.SQL_WVARCHAR: [],
        }
