from collections.abc import Mapping
from functools import partial
from typing import Any

import pytest

from odbcffi.odbc.enums import InfoType, SQLDataType
from tests.drivers.base import DriverTest

# TODO: Sort out MDAC tests
pytestmark = pytest.mark.skip("TODO: Sort out MDAC tests")
# pytestmark = pytest.mark.skipif(platform.system() != "Windows", reason="MDAC is Windows only.")


@pytest.fixture(scope="module")
def driver() -> str:
    return "SQL Server"


class TestMDAC(DriverTest):
    @property
    def expected_sql_get_info_w_return_values(self) -> Mapping[InfoType, Any]:
        return {
            InfoType.SQL_ACCESSIBLE_PROCEDURES: "",
            InfoType.SQL_ACCESSIBLE_TABLES: "",
            InfoType.SQL_ACTIVE_ENVIRONMENTS: "",
            InfoType.SQL_AGGREGATE_FUNCTIONS: "",
            InfoType.SQL_ALTER_DOMAIN: "",
            InfoType.SQL_ALTER_TABLE: "",
            InfoType.SQL_ASYNC_DBC_FUNCTIONS: "",
            InfoType.SQL_ASYNC_MODE: "",
            InfoType.SQL_ASYNC_NOTIFICATION: "",
            InfoType.SQL_BATCH_ROW_COUNT: "",
            InfoType.SQL_BATCH_SUPPORT: "",
            InfoType.SQL_BOOKMARK_PERSISTENCE: "",
            InfoType.SQL_CATALOG_LOCATION: "",
            InfoType.SQL_CATALOG_NAME: "",
            InfoType.SQL_CATALOG_NAME_SEPARATOR: "",
            InfoType.SQL_CATALOG_TERM: "",
            InfoType.SQL_CATALOG_USAGE: "",
            InfoType.SQL_COLLATION_SEQ: "",
            InfoType.SQL_COLUMN_ALIAS: "",
            InfoType.SQL_CONCAT_NULL_BEHAVIOR: "",
            InfoType.SQL_CONVERT_BIGINT: "",
            InfoType.SQL_CONVERT_BINARY: "",
            InfoType.SQL_CONVERT_BIT: "",
            InfoType.SQL_CONVERT_CHAR: "",
            InfoType.SQL_CONVERT_DATE: "",
            InfoType.SQL_CONVERT_DECIMAL: "",
            InfoType.SQL_CONVERT_DOUBLE: "",
            InfoType.SQL_CONVERT_FLOAT: "",
            InfoType.SQL_CONVERT_FUNCTIONS: "",
            InfoType.SQL_CONVERT_GUID: "",
            InfoType.SQL_CONVERT_INTEGER: "",
            InfoType.SQL_CONVERT_INTERVAL_DAY_TIME: "",
            InfoType.SQL_CONVERT_INTERVAL_YEAR_MONTH: "",
            InfoType.SQL_CONVERT_LONGVARBINARY: "",
            InfoType.SQL_CONVERT_LONGVARCHAR: "",
            InfoType.SQL_CONVERT_NUMERIC: "",
            InfoType.SQL_CONVERT_REAL: "",
            InfoType.SQL_CONVERT_SMALLINT: "",
            InfoType.SQL_CONVERT_TIME: "",
            InfoType.SQL_CONVERT_TIMESTAMP: "",
            InfoType.SQL_CONVERT_TINYINT: "",
            InfoType.SQL_CONVERT_VARBINARY: "",
            InfoType.SQL_CONVERT_VARCHAR: "",
            InfoType.SQL_CONVERT_WCHAR: "",
            InfoType.SQL_CONVERT_WLONGVARCHAR: "",
            InfoType.SQL_CONVERT_WVARCHAR: "",
            InfoType.SQL_CORRELATION_NAME: "",
            InfoType.SQL_CREATE_ASSERTION: "",
            InfoType.SQL_CREATE_CHARACTER_SET: "",
            InfoType.SQL_CREATE_COLLATION: "",
            InfoType.SQL_CREATE_DOMAIN: "",
            InfoType.SQL_CREATE_SCHEMA: "",
            InfoType.SQL_CREATE_TABLE: "",
            InfoType.SQL_CREATE_TRANSLATION: "",
            InfoType.SQL_CREATE_VIEW: "",
            InfoType.SQL_CURSOR_COMMIT_BEHAVIOR: "",
            InfoType.SQL_CURSOR_ROLLBACK_BEHAVIOR: "",
            InfoType.SQL_CURSOR_SENSITIVITY: "",
            InfoType.SQL_DATABASE_NAME: "",
            InfoType.SQL_DATA_SOURCE_NAME: "",
            InfoType.SQL_DATA_SOURCE_READ_ONLY: "",
            InfoType.SQL_DATETIME_LITERALS: "",
            InfoType.SQL_DBMS_NAME: "",
            InfoType.SQL_DBMS_VER: partial(pytest.skip, reason="Unstable return value for SQL_DBMS_VER"),
            InfoType.SQL_DDL_INDEX: "",
            InfoType.SQL_DEFAULT_TXN_ISOLATION: "",
            InfoType.SQL_DESCRIBE_PARAMETER: "",
            InfoType.SQL_DM_VER: partial(pytest.skip, reason="Unstable return value for SQL_DM_VER"),
            InfoType.SQL_DRIVER_AWARE_POOLING_SUPPORTED: "",
            InfoType.SQL_DRIVER_HDBC: "",
            InfoType.SQL_DRIVER_HDESC: "",
            InfoType.SQL_DRIVER_HENV: "",
            InfoType.SQL_DRIVER_HLIB: "",
            InfoType.SQL_DRIVER_HSTMT: "",
            InfoType.SQL_DRIVER_NAME: partial(pytest.skip, reason="Unstable return value for SQL_DRIVER_NAME"),
            InfoType.SQL_DRIVER_ODBC_VER: "",
            InfoType.SQL_DRIVER_VER: partial(pytest.skip, reason="Unstable return value for SQL_DRIVER_VER"),
            InfoType.SQL_DROP_ASSERTION: "",
            InfoType.SQL_DROP_CHARACTER_SET: "",
            InfoType.SQL_DROP_COLLATION: "",
            InfoType.SQL_DROP_DOMAIN: "",
            InfoType.SQL_DROP_SCHEMA: "",
            InfoType.SQL_DROP_TABLE: "",
            InfoType.SQL_DROP_TRANSLATION: "",
            InfoType.SQL_DROP_VIEW: "",
            InfoType.SQL_DYNAMIC_CURSOR_ATTRIBUTES1: "",
            InfoType.SQL_DYNAMIC_CURSOR_ATTRIBUTES2: "",
            InfoType.SQL_EXPRESSIONS_IN_ORDERBY: "",
            InfoType.SQL_FETCH_DIRECTION: "",
            InfoType.SQL_FILE_USAGE: "",
            InfoType.SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES1: "",
            InfoType.SQL_FORWARD_ONLY_CURSOR_ATTRIBUTES2: "",
            InfoType.SQL_GETDATA_EXTENSIONS: "",
            InfoType.SQL_GROUP_BY: "",
            InfoType.SQL_IDENTIFIER_CASE: "",
            InfoType.SQL_IDENTIFIER_QUOTE_CHAR: "",
            InfoType.SQL_INDEX_KEYWORDS: "",
            InfoType.SQL_INFO_SCHEMA_VIEWS: "",
            InfoType.SQL_INSERT_STATEMENT: "",
            InfoType.SQL_INTEGRITY: "",
            InfoType.SQL_KEYSET_CURSOR_ATTRIBUTES1: "",
            InfoType.SQL_KEYSET_CURSOR_ATTRIBUTES2: "",
            InfoType.SQL_KEYWORDS: "",
            InfoType.SQL_LIKE_ESCAPE_CLAUSE: "",
            InfoType.SQL_LOCK_TYPES: "",
            InfoType.SQL_MAX_ASYNC_CONCURRENT_STATEMENTS: "",
            InfoType.SQL_MAX_BINARY_LITERAL_LEN: "",
            InfoType.SQL_MAX_CATALOG_NAME_LEN: "",
            InfoType.SQL_MAX_CHAR_LITERAL_LEN: "",
            InfoType.SQL_MAX_COLUMNS_IN_GROUP_BY: "",
            InfoType.SQL_MAX_COLUMNS_IN_INDEX: "",
            InfoType.SQL_MAX_COLUMNS_IN_ORDER_BY: "",
            InfoType.SQL_MAX_COLUMNS_IN_SELECT: "",
            InfoType.SQL_MAX_COLUMNS_IN_TABLE: "",
            InfoType.SQL_MAX_COLUMN_NAME_LEN: "",
            InfoType.SQL_MAX_CONCURRENT_ACTIVITIES: "",
            InfoType.SQL_MAX_CURSOR_NAME_LEN: "",
            InfoType.SQL_MAX_DRIVER_CONNECTIONS: "",
            InfoType.SQL_MAX_IDENTIFIER_LEN: "",
            InfoType.SQL_MAX_INDEX_SIZE: "",
            InfoType.SQL_MAX_PROCEDURE_NAME_LEN: "",
            InfoType.SQL_MAX_ROW_SIZE: "",
            InfoType.SQL_MAX_ROW_SIZE_INCLUDES_LONG: "",
            InfoType.SQL_MAX_SCHEMA_NAME_LEN: "",
            InfoType.SQL_MAX_STATEMENT_LEN: "",
            InfoType.SQL_MAX_TABLES_IN_SELECT: "",
            InfoType.SQL_MAX_TABLE_NAME_LEN: "",
            InfoType.SQL_MAX_USER_NAME_LEN: "",
            InfoType.SQL_MULTIPLE_ACTIVE_TXN: "",
            InfoType.SQL_MULT_RESULT_SETS: "",
            InfoType.SQL_NEED_LONG_DATA_LEN: "",
            InfoType.SQL_NON_NULLABLE_COLUMNS: "",
            InfoType.SQL_NULL_COLLATION: "",
            InfoType.SQL_NUMERIC_FUNCTIONS: "",
            InfoType.SQL_ODBC_API_CONFORMANCE: "",
            InfoType.SQL_ODBC_INTERFACE_CONFORMANCE: "",
            InfoType.SQL_ODBC_SAG_CLI_CONFORMANCE: "",
            InfoType.SQL_ODBC_SQL_CONFORMANCE: "",
            InfoType.SQL_ODBC_VER: "",
            InfoType.SQL_OJ_CAPABILITIES: "",
            InfoType.SQL_ORDER_BY_COLUMNS_IN_SELECT: "",
            InfoType.SQL_OUTER_JOINS: "",
            InfoType.SQL_PARAM_ARRAY_ROW_COUNTS: "",
            InfoType.SQL_PARAM_ARRAY_SELECTS: "",
            InfoType.SQL_POSITIONED_STATEMENTS: "",
            InfoType.SQL_POS_OPERATIONS: "",
            InfoType.SQL_PROCEDURES: "",
            InfoType.SQL_PROCEDURE_TERM: "",
            InfoType.SQL_QUOTED_IDENTIFIER_CASE: "",
            InfoType.SQL_ROW_UPDATES: "",
            InfoType.SQL_SCHEMA_TERM: "",
            InfoType.SQL_SCHEMA_USAGE: "",
            InfoType.SQL_SCROLL_CONCURRENCY: "",
            InfoType.SQL_SCROLL_OPTIONS: "",
            InfoType.SQL_SEARCH_PATTERN_ESCAPE: "",
            InfoType.SQL_SERVER_NAME: partial(pytest.skip, reason="Unstable return value for SQL_SERVER_NAME"),
            InfoType.SQL_SPECIAL_CHARACTERS: "",
            InfoType.SQL_SQL92_DATETIME_FUNCTIONS: "",
            InfoType.SQL_SQL92_FOREIGN_KEY_DELETE_RULE: "",
            InfoType.SQL_SQL92_FOREIGN_KEY_UPDATE_RULE: "",
            InfoType.SQL_SQL92_GRANT: "",
            InfoType.SQL_SQL92_NUMERIC_VALUE_FUNCTIONS: "",
            InfoType.SQL_SQL92_PREDICATES: "",
            InfoType.SQL_SQL92_RELATIONAL_JOIN_OPERATORS: "",
            InfoType.SQL_SQL92_REVOKE: "",
            InfoType.SQL_SQL92_ROW_VALUE_CONSTRUCTOR: "",
            InfoType.SQL_SQL92_STRING_FUNCTIONS: "",
            InfoType.SQL_SQL92_VALUE_EXPRESSIONS: "",
            InfoType.SQL_SQL_CONFORMANCE: "",
            InfoType.SQL_STANDARD_CLI_CONFORMANCE: "",
            InfoType.SQL_STATIC_CURSOR_ATTRIBUTES1: "",
            InfoType.SQL_STATIC_CURSOR_ATTRIBUTES2: "",
            InfoType.SQL_STATIC_SENSITIVITY: "",
            InfoType.SQL_STRING_FUNCTIONS: "",
            InfoType.SQL_SUBQUERIES: "",
            InfoType.SQL_SYSTEM_FUNCTIONS: "",
            InfoType.SQL_TABLE_TERM: "",
            InfoType.SQL_TIMEDATE_ADD_INTERVALS: "",
            InfoType.SQL_TIMEDATE_DIFF_INTERVALS: "",
            InfoType.SQL_TIMEDATE_FUNCTIONS: "",
            InfoType.SQL_TXN_CAPABLE: "",
            InfoType.SQL_TXN_ISOLATION_OPTION: "",
            InfoType.SQL_UNION: "",
            InfoType.SQL_USER_NAME: "",
            InfoType.SQL_XOPEN_CLI_YEAR: "",
        }

    @property
    def expected_sql_get_type_info_w_return_values(self) -> Mapping[SQLDataType, list[dict[str, Any]]]:
        return {
            SQLDataType.SQL_BIGINT: [],
            SQLDataType.SQL_BINARY: [],
            SQLDataType.SQL_BIT: [],
            SQLDataType.SQL_CHAR: [],
            SQLDataType.SQL_DATETIME: [],
            SQLDataType.SQL_DECIMAL: [],
            SQLDataType.SQL_DOUBLE: [],
            SQLDataType.SQL_FLOAT: [],
            SQLDataType.SQL_GUID: [],
            SQLDataType.SQL_INTEGER: [],
            SQLDataType.SQL_INTERVAL: [],
            SQLDataType.SQL_LONGVARBINARY: [],
            SQLDataType.SQL_LONGVARCHAR: [],
            SQLDataType.SQL_NUMERIC: [],
            SQLDataType.SQL_REAL: [],
            SQLDataType.SQL_SMALLINT: [],
            SQLDataType.SQL_SS_TABLE: [],
            SQLDataType.SQL_SS_TIME2: [],
            SQLDataType.SQL_SS_TIMESTAMPOFFSET: [],
            SQLDataType.SQL_SS_UDT: [],
            SQLDataType.SQL_SS_VARIANT: [],
            SQLDataType.SQL_SS_XML: [],
            SQLDataType.SQL_TIMESTAMP: [],
            SQLDataType.SQL_TINYINT: [],
            SQLDataType.SQL_TYPE_DATE: [],
            SQLDataType.SQL_TYPE_TIME: [],
            SQLDataType.SQL_TYPE_TIME_WITH_TIMEZONE: [],
            SQLDataType.SQL_TYPE_TIMESTAMP: [],
            SQLDataType.SQL_TYPE_TIMESTAMP_WITH_TIMEZONE: [],
            SQLDataType.SQL_UNKNOWN_TYPE: [
                {
                    "TYPE_NAME": "sql_variant",
                    "DATA_TYPE": SQLDataType.SQL_SS_VARIANT,
                    "COLUMN_SIZE": 8000,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "sql_variant",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": -150,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "uniqueidentifier",
                    "DATA_TYPE": SQLDataType.SQL_GUID,
                    "COLUMN_SIZE": 36,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "uniqueidentifier",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -11,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "ntext",
                    "DATA_TYPE": SQLDataType.SQL_WLONGVARCHAR,
                    "COLUMN_SIZE": 1073741823,
                    "LITERAL_PREFIX": "N'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 1,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "ntext",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -10,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "xml",
                    "DATA_TYPE": SQLDataType.SQL_WLONGVARCHAR,
                    "COLUMN_SIZE": 1073741823,
                    "LITERAL_PREFIX": "N'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 1,
                    "SEARCHABLE": 0,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "xml",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -10,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "nvarchar",
                    "DATA_TYPE": SQLDataType.SQL_WVARCHAR,
                    "COLUMN_SIZE": 4000,
                    "LITERAL_PREFIX": "N'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": "max length",
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "nvarchar",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -9,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "sysname",
                    "DATA_TYPE": SQLDataType.SQL_WVARCHAR,
                    "COLUMN_SIZE": 128,
                    "LITERAL_PREFIX": "N'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 0,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "sysname",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -9,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 18,
                },
                {
                    "TYPE_NAME": "date",
                    "DATA_TYPE": SQLDataType.SQL_WVARCHAR,
                    "COLUMN_SIZE": 10,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "date",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -9,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "time",
                    "DATA_TYPE": SQLDataType.SQL_WVARCHAR,
                    "COLUMN_SIZE": 16,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "time",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -9,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "datetime2",
                    "DATA_TYPE": SQLDataType.SQL_WVARCHAR,
                    "COLUMN_SIZE": 27,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "datetime2",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -9,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "datetimeoffset",
                    "DATA_TYPE": SQLDataType.SQL_WVARCHAR,
                    "COLUMN_SIZE": 34,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "datetimeoffset",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -9,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "nchar",
                    "DATA_TYPE": SQLDataType.SQL_WCHAR,
                    "COLUMN_SIZE": 4000,
                    "LITERAL_PREFIX": "N'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": "length",
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "nchar",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -8,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "bit",
                    "DATA_TYPE": SQLDataType.SQL_BIT,
                    "COLUMN_SIZE": 1,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "bit",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": -7,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 16,
                },
                {
                    "TYPE_NAME": "tinyint",
                    "DATA_TYPE": SQLDataType.SQL_TINYINT,
                    "COLUMN_SIZE": 3,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 1,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "tinyint",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": -6,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 5,
                },
                {
                    "TYPE_NAME": "tinyint identity",
                    "DATA_TYPE": SQLDataType.SQL_TINYINT,
                    "COLUMN_SIZE": 3,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 0,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 1,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 1,
                    "LOCAL_TYPE_NAME": "tinyint identity",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": -6,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 5,
                },
                {
                    "TYPE_NAME": "bigint",
                    "DATA_TYPE": SQLDataType.SQL_BIGINT,
                    "COLUMN_SIZE": 19,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "bigint",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": -5,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "bigint identity",
                    "DATA_TYPE": SQLDataType.SQL_BIGINT,
                    "COLUMN_SIZE": 19,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 0,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 1,
                    "LOCAL_TYPE_NAME": "bigint identity",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": -5,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 0,
                },
                {
                    "TYPE_NAME": "image",
                    "DATA_TYPE": SQLDataType.SQL_LONGVARBINARY,
                    "COLUMN_SIZE": 2147483647,
                    "LITERAL_PREFIX": "0x",
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 0,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "image",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -4,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 20,
                },
                {
                    "TYPE_NAME": "varbinary",
                    "DATA_TYPE": SQLDataType.SQL_VARBINARY,
                    "COLUMN_SIZE": 8000,
                    "LITERAL_PREFIX": "0x",
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": "max length",
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "varbinary",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -3,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 4,
                },
                {
                    "TYPE_NAME": "binary",
                    "DATA_TYPE": SQLDataType.SQL_BINARY,
                    "COLUMN_SIZE": 8000,
                    "LITERAL_PREFIX": "0x",
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": "length",
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "binary",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -2,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 3,
                },
                {
                    "TYPE_NAME": "timestamp",
                    "DATA_TYPE": SQLDataType.SQL_BINARY,
                    "COLUMN_SIZE": 8,
                    "LITERAL_PREFIX": "0x",
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 0,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "timestamp",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -2,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 80,
                },
                {
                    "TYPE_NAME": "text",
                    "DATA_TYPE": SQLDataType.SQL_LONGVARCHAR,
                    "COLUMN_SIZE": 2147483647,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 1,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "text",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": -1,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 19,
                },
                {
                    "TYPE_NAME": "char",
                    "DATA_TYPE": SQLDataType.SQL_CHAR,
                    "COLUMN_SIZE": 8000,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": "length",
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "char",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": 1,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 1,
                },
                {
                    "TYPE_NAME": "numeric",
                    "DATA_TYPE": SQLDataType.SQL_NUMERIC,
                    "COLUMN_SIZE": 38,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": "precision,scale",
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "numeric",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 38,
                    "SQL_DATA_TYPE": 2,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 10,
                },
                {
                    "TYPE_NAME": "numeric() identity",
                    "DATA_TYPE": SQLDataType.SQL_NUMERIC,
                    "COLUMN_SIZE": 38,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": "precision",
                    "NULLABLE": 0,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 1,
                    "LOCAL_TYPE_NAME": "numeric() identity",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": 2,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 10,
                },
                {
                    "TYPE_NAME": "decimal",
                    "DATA_TYPE": SQLDataType.SQL_DECIMAL,
                    "COLUMN_SIZE": 38,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": "precision,scale",
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "decimal",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 38,
                    "SQL_DATA_TYPE": 3,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 24,
                },
                {
                    "TYPE_NAME": "money",
                    "DATA_TYPE": SQLDataType.SQL_DECIMAL,
                    "COLUMN_SIZE": 19,
                    "LITERAL_PREFIX": "$",
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 1,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "money",
                    "MINIMUM_SCALE": 4,
                    "MAXIMUM_SCALE": 4,
                    "SQL_DATA_TYPE": 3,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 11,
                },
                {
                    "TYPE_NAME": "smallmoney",
                    "DATA_TYPE": SQLDataType.SQL_DECIMAL,
                    "COLUMN_SIZE": 10,
                    "LITERAL_PREFIX": "$",
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 1,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "smallmoney",
                    "MINIMUM_SCALE": 4,
                    "MAXIMUM_SCALE": 4,
                    "SQL_DATA_TYPE": 3,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 21,
                },
                {
                    "TYPE_NAME": "decimal() identity",
                    "DATA_TYPE": SQLDataType.SQL_DECIMAL,
                    "COLUMN_SIZE": 38,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": "precision",
                    "NULLABLE": 0,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 1,
                    "LOCAL_TYPE_NAME": "decimal() identity",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": 3,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 24,
                },
                {
                    "TYPE_NAME": "int",
                    "DATA_TYPE": SQLDataType.SQL_INTEGER,
                    "COLUMN_SIZE": 10,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "int",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": 4,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 7,
                },
                {
                    "TYPE_NAME": "int identity",
                    "DATA_TYPE": SQLDataType.SQL_INTEGER,
                    "COLUMN_SIZE": 10,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 0,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 1,
                    "LOCAL_TYPE_NAME": "int identity",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": 4,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 7,
                },
                {
                    "TYPE_NAME": "smallint",
                    "DATA_TYPE": SQLDataType.SQL_SMALLINT,
                    "COLUMN_SIZE": 5,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "smallint",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": 5,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 6,
                },
                {
                    "TYPE_NAME": "smallint identity",
                    "DATA_TYPE": SQLDataType.SQL_SMALLINT,
                    "COLUMN_SIZE": 5,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 0,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 1,
                    "LOCAL_TYPE_NAME": "smallint identity",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": 5,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 10,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 6,
                },
                {
                    "TYPE_NAME": "float",
                    "DATA_TYPE": SQLDataType.SQL_FLOAT,
                    "COLUMN_SIZE": 53,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "float",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": 6,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 2,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 8,
                },
                {
                    "TYPE_NAME": "real",
                    "DATA_TYPE": SQLDataType.SQL_REAL,
                    "COLUMN_SIZE": 24,
                    "LITERAL_PREFIX": None,
                    "LITERAL_SUFFIX": None,
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 2,
                    "UNSIGNED_ATTRIBUTE": 0,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": 0,
                    "LOCAL_TYPE_NAME": "real",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": 7,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": 2,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 23,
                },
                {
                    "TYPE_NAME": "varchar",
                    "DATA_TYPE": SQLDataType.SQL_VARCHAR,
                    "COLUMN_SIZE": 8000,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": "max length",
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "varchar",
                    "MINIMUM_SCALE": None,
                    "MAXIMUM_SCALE": None,
                    "SQL_DATA_TYPE": 12,
                    "SQL_DATETIME_SUB": None,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 2,
                },
                {
                    "TYPE_NAME": "datetime",
                    "DATA_TYPE": SQLDataType.SQL_TYPE_TIMESTAMP,
                    "COLUMN_SIZE": 23,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "datetime",
                    "MINIMUM_SCALE": 3,
                    "MAXIMUM_SCALE": 3,
                    "SQL_DATA_TYPE": 9,
                    "SQL_DATETIME_SUB": SQLDataType.SQL_DECIMAL,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 12,
                },
                {
                    "TYPE_NAME": "smalldatetime",
                    "DATA_TYPE": SQLDataType.SQL_TYPE_TIMESTAMP,
                    "COLUMN_SIZE": 16,
                    "LITERAL_PREFIX": "'",
                    "LITERAL_SUFFIX": "'",
                    "CREATE_PARAMS": None,
                    "NULLABLE": 1,
                    "CASE_SENSITIVE": 0,
                    "SEARCHABLE": 3,
                    "UNSIGNED_ATTRIBUTE": None,
                    "FIXED_PREC_SCALE": 0,
                    "AUTO_UNIQUE_VALUE": None,
                    "LOCAL_TYPE_NAME": "smalldatetime",
                    "MINIMUM_SCALE": 0,
                    "MAXIMUM_SCALE": 0,
                    "SQL_DATA_TYPE": 9,
                    "SQL_DATETIME_SUB": SQLDataType.SQL_DECIMAL,
                    "NUM_PREC_RADIX": None,
                    "INTERVAL_PRECISION": None,
                    "USERTYPE": 22,
                },
            ],
            SQLDataType.SQL_VARBINARY: [],
            SQLDataType.SQL_VARCHAR: [],
            SQLDataType.SQL_WCHAR: [],
            SQLDataType.SQL_WLONGVARCHAR: [],
            SQLDataType.SQL_WVARCHAR: [],
        }
